version: 0.2

phases:
  install:
    runtime-versions:
      runtime: nodejs8.10
    commands:
      - echo installing serverless 
      - npm install -g serverless
  pre_build:
    commands:
      - echo installing npm packages
      - npm install
  build:
    commands:
      - echo build started at `date`
      - echo deploying with serverless
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo deployment completed at `date`